---
- name: Create avalanche data directory
  ansible.builtin.file:
    path: "{{ avago_data_dir }}/data"
    state: directory
    owner: 1000 # Default docker user, adjust if needed
    group: 1000
    mode: '0755'

- name: Create avalanche config directory
  ansible.builtin.file:
    path: "{{ avago_config_dir }}"
    state: directory
    mode: '0755'

- name: Template avalanchego config file
  ansible.builtin.template:
    src: config.json.j2
    dest: "{{ avago_config_file }}"
    mode: '0644'
  notify:
  - Restart avalanchego

- name: Template docker-compose file
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ avago_docker_compose_file }}"
    mode: '0644'
  notify:
  - Restart avalanchego

- name: Deploy and start avalanchego container
  community.docker.docker_compose_v2:
    project_src: "{{ avago_data_dir }}"
    files:
      - docker-compose.yml
    state: present

- name: Copy node verification script
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../tests/verify_node_deployment.py"
    dest: "/tmp/verify_node_deployment.py"
    mode: '0755'

- name: Run node verification script
  ansible.builtin.command:
    cmd: python3 /tmp/verify_node_deployment.py
  register: verification_result
  changed_when: false
  failed_when: verification_result.rc != 0

- name: Display verification results
  ansible.builtin.debug:
    msg: "{{ verification_result.stdout_lines }}"