---
- name: Deploy Avalanche Fuji Validator
  hosts: validators
  become: yes
  vars:
    # Ensure python3 is used
    ansible_python_interpreter: /usr/bin/python3

  pre_tasks:
    - name: Update apt cache and install prerequisites
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
        update_cache: yes
        state: present

    - name: Install Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
        state: present

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin # Note: a-v-a uses docker-compose, not the plugin
        state: present
        update_cache: yes

    - name: Install Python Docker library (for Ansible modules)
      ansible.builtin.pip:
        name:
          - docker
          - docker-compose # The classic docker-compose
        state: present

    - name: Ensure Docker service is started
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

  roles:
    - role: docker-node